
spring:
 mvc:
  hiddenmethod:
   filter:
    enabled: true
 thymeleaf:
  enabled: true
  prefix: classpath:/templates/
 datasource:
  url: jdbc:mysql://localhost:3306/student_db
  username: root
  password: rainbow
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   database: mysql
   database-platform: org.hibernate.dialect.MySQLDialect
   show-sql: true
   hibernate:
    ddl-auto: none
   properties:
    hibernate:
     format_sql: true
